### ISSUE TITLE
BUTTON CHILDREN[BUG]: 

### ISSUE THREAD

**Issue by MsingathiMat** [attlr-ui/ui-components#36]
**Describe the bug**

The button does not accept a string as a child, can it accept children as ReactNodes so that the string can be acceptable so that we can push the color style as a prop. This is my view of a button component --> It must have the following out of the box, Props for TEXT COLOR, BACKGROUND COLOR, IDEAL PADDING (That works well if not changed), CALLBACK EVENT, LOADING STATE etc. In summary, i dont like to style a button, meaning custom style...  i must plug it an play without configuring 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Axolem** [comment]
- onPress for the call back
- loading for the loading state
- Props for text color? You pass your own text component meaning you can style the text the way you want
See:
```ts
<AButton

          fill='solid'
          loadingColor='green'
          size='full'
          iconRight={<AntDesign name="upcircle" size={24} color="white" />}
          icon
        // loading={true}
        >
          <AButtonText variant='default'>Click</AButtonText>
        </AButton>
```

- [ ] Will add `padding`
- [ ] `bg` prop

**Comment by MsingathiMat** [comment]
Ok thanks, What used to work for me also is.   Mandatory props, i noticed that i can add a component without getting TS complaints. These mandatory props helps with assisting the user to get started, they prompt you to fill in or show you what's needed to get the component's default
